[pytest]

# 把当前项目根目录加入 Python 模块搜索路径。
# 这样测试文件就能导入 src.config、src.entities 等模块。
pythonpath = .

# 指定 pytest 只在 tests 文件夹中寻找测试。
testpaths = tests

# 测试文件的命名规则。
python_files = test_*.py

# 测试函数的命名规则。
python_functions = test_*